"""empty message

Revision ID: 8467b4aa456c
Revises: 
Create Date: 2019-12-30 14:34:29.245947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8467b4aa456c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=256), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=256), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable')
    op.drop_table('team')
    # ### end Alembic commands ###
